# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mnc Patrol Effort
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    rewrite_file_urls_for_screenshots as rewrite_file_urls_for_screenshots,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mep.tasks import gdf_to_geojson as gdf_to_geojson
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import compute_occupancy as compute_occupancy
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_patrol_coverage_grid as create_patrol_coverage_grid,
)
from ecoscope_workflows_ext_mnc.tasks import (
    custom_get_patrol_observations_from_patrols_df as custom_get_patrol_observations_from_patrols_df,
)
from ecoscope_workflows_ext_mnc.tasks import (
    explode_multiple_columns as explode_multiple_columns,
)
from ecoscope_workflows_ext_mnc.tasks import (
    filter_non_empty_values as filter_non_empty_values,
)
from ecoscope_workflows_ext_mnc.tasks import get_patrol_values as get_patrol_values
from ecoscope_workflows_ext_mnc.tasks import map_name_values as map_name_values
from ecoscope_workflows_ext_mnc.tasks import merge_dataframes as merge_dataframes
from ecoscope_workflows_ext_mnc.tasks import merge_multiple_df as merge_multiple_df
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import round_values as round_values
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type_1,
)
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type_1
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Configure base map layers

# %%
# parameters

configure_base_maps_params = dict()

# %%
# call the task


configure_base_maps = (
    set_base_maps_pydeck.set_task_instance_id("configure_base_maps")
    .handle_errors()
    .with_tracing()
    .partial(
        base_maps=[
            {
                "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            }
        ],
        **configure_base_maps_params,
    )
    .call()
)


# %% [markdown]
# ## Download MNC community conservancy boundaries

# %%
# parameters

persist_mnc_gpkg_params = dict()

# %%
# call the task


persist_mnc_gpkg = (
    fetch_and_persist_file.set_task_instance_id("persist_mnc_gpkg")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_mnc_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Download MNC Parcels gpkg

# %%
# parameters

download_mnc_parcels_params = dict()

# %%
# call the task


download_mnc_parcels = (
    fetch_and_persist_file.set_task_instance_id("download_mnc_parcels")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **download_mnc_parcels_params,
    )
    .call()
)


# %% [markdown]
# ## Load community conservancy boundaries

# %%
# parameters

load_comm_shp_params = dict()

# %%
# call the task


load_comm_shp = (
    load_df.set_task_instance_id("load_comm_shp")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=persist_mnc_gpkg,
        layer=None,
        deserialize_json=False,
        **load_comm_shp_params,
    )
    .call()
)


# %% [markdown]
# ## Split loaded gdf by various grazing zones and blocks

# %%
# parameters

split_gdf_by_zone_params = dict()

# %%
# call the task


split_gdf_by_zone = (
    split_gdf_by_column.set_task_instance_id("split_gdf_by_zone")
    .handle_errors()
    .with_tracing()
    .partial(gdf=load_comm_shp, column="grazing_zone", **split_gdf_by_zone_params)
    .call()
)


# %% [markdown]
# ## Annotate community conservancy gpkg with geom type

# %%
# parameters

annotate_comm_gdf_dict_params = dict()

# %%
# call the task


annotate_comm_gdf_dict = (
    annotate_gdf_dict_with_geom_type_1.set_task_instance_id("annotate_comm_gdf_dict")
    .handle_errors()
    .with_tracing()
    .partial(gdf_dict=split_gdf_by_zone, **annotate_comm_gdf_dict_params)
    .call()
)


# %% [markdown]
# ## Create styled layers from split mnc zones

# %%
# parameters

create_mnc_styled_layers_params = dict()

# %%
# call the task


create_mnc_styled_layers = (
    create_deckgl_layers_from_gdf_dict.set_task_instance_id("create_mnc_styled_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        gdf_dict=annotate_comm_gdf_dict,
        styles={
            "Conservancy": {
                "extruded": False,
                "get_fill_color": [169, 169, 169],
                "get_line_color": [169, 169, 169],
                "get_line_width": 4.0,
                "stroked": True,
                "filled": False,
                "opacity": 0.95,
            },
            "Conservancy Herd Zone": {
                "extruded": False,
                "get_fill_color": [173, 255, 47],
                "get_line_color": [173, 255, 47],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 1": {
                "extruded": False,
                "get_fill_color": [85, 107, 47],
                "get_line_color": [85, 107, 47],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 2": {
                "extruded": False,
                "get_fill_color": [0, 139, 139],
                "get_line_color": [0, 139, 139],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 3": {
                "extruded": False,
                "get_fill_color": [0, 100, 0],
                "get_line_color": [0, 100, 0],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 4": {
                "extruded": False,
                "get_fill_color": [143, 188, 139],
                "get_line_color": [143, 188, 139],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
        },
        legends={
            "title": "Legend",
            "values": [
                {"label": "Conservancy", "color": "#a9a9a9"},
                {"label": "Conservancy Herd Zone", "color": "#adff2f"},
                {"label": "Grazing Zone 1", "color": "#556b2f"},
                {"label": "Grazing Zone 2", "color": "#008b8b"},
                {"label": "Grazing Zone 3", "color": "#006400"},
                {"label": "Grazing Zone 4", "color": "#8fbc8b"},
            ],
        },
        **create_mnc_styled_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy boundaries

# %%
# parameters

create_conservancy_boundaries_params = dict()

# %%
# call the task


create_conservancy_boundaries = (
    create_deckgl_layers_from_gdf_dict.set_task_instance_id(
        "create_conservancy_boundaries"
    )
    .handle_errors()
    .with_tracing()
    .partial(
        gdf_dict=annotate_comm_gdf_dict,
        styles={
            "Conservancy": {
                "extruded": False,
                "get_fill_color": [169, 169, 169],
                "get_line_color": [169, 169, 169],
                "get_line_width": 4.0,
                "stroked": True,
                "filled": False,
                "opacity": 0.95,
            }
        },
        legends={
            "title": "Legend",
            "values": [{"label": "Boundaries", "color": "#a9a9a9"}],
        },
        **create_conservancy_boundaries_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy gdf from split dict

# %%
# parameters

conservancy_gdf_params = dict()

# %%
# call the task


conservancy_gdf = (
    create_gdf_from_dict.set_task_instance_id("conservancy_gdf")
    .handle_errors()
    .with_tracing()
    .partial(gdf_dict=split_gdf_by_zone, key="Conservancy", **conservancy_gdf_params)
    .call()
)


# %% [markdown]
# ## Create group ranch gdf from loaded gdf

# %%
# parameters

overall_grazing_zones_params = dict()

# %%
# call the task


overall_grazing_zones = (
    filter_df.set_task_instance_id("overall_grazing_zones")
    .handle_errors()
    .with_tracing()
    .partial(
        column_name="grazing_zone",
        op="ne",
        value="Conservancy",
        df=load_comm_shp,
        reset_index=False,
        **overall_grazing_zones_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy text layers here

# %%
# parameters

conservancy_text_layer_params = dict()

# %%
# call the task


conservancy_text_layer = (
    create_custom_text_layer.set_task_instance_id("conservancy_text_layer")
    .handle_errors()
    .with_tracing()
    .partial(
        geodataframe=conservancy_gdf,
        layer_style={
            "get_text": "name",
            "get_color": [0, 0, 0, 255],
            "get_size": 1500,
            "size_units": "meters",
            "size_min_pixels": 70,
            "size_max_pixels": 100,
            "size_scale": 2.25,
            "font_family": "Calibri",
            "font_weight": "700",
            "get_text_anchor": "middle",
            "get_alignment_baseline": "center",
            "billboard": True,
            "background_padding": [4, 8],
            "pickable": True,
            "auto_highlight": False,
        },
        use_centroid=True,
        legend=None,
        **conservancy_text_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Load mnc parcels

# %%
# parameters

load_mnc_parcels_params = dict()

# %%
# call the task


load_mnc_parcels = (
    load_df.set_task_instance_id("load_mnc_parcels")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=download_mnc_parcels,
        layer=None,
        deserialize_json=False,
        **load_mnc_parcels_params,
    )
    .call()
)


# %% [markdown]
# ## Assign geom type to mnc parcels

# %%
# parameters

assign_mnc_geom_params = dict()

# %%
# call the task


assign_mnc_geom = (
    get_gdf_geom_type_1.set_task_instance_id("assign_mnc_geom")
    .handle_errors()
    .with_tracing()
    .partial(gdf=load_mnc_parcels, **assign_mnc_geom_params)
    .call()
)


# %% [markdown]
# ## Create mnc parcels layers

# %%
# parameters

create_mnc_parcels_layers_params = dict()

# %%
# call the task


create_mnc_parcels_layers = (
    create_deckgl_layer_from_gdf.set_task_instance_id("create_mnc_parcels_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        gdf=assign_mnc_geom,
        style={
            "extruded": False,
            "get_fill_color": [189, 183, 107],
            "get_line_color": [189, 183, 107],
            "get_line_width": 1.95,
            "stroked": True,
            "filled": True,
            "opacity": 0.15,
        },
        legend={"title": "", "values": [{"label": "Parcels", "color": "#bdb76b"}]},
        **create_mnc_parcels_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve all events

# %%
# parameters

get_events_data_params = dict()

# %%
# call the task


get_events_data = (
    get_events.set_task_instance_id("get_events_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "created_at",
            "event_details",
            "patrols",
        ],
        event_types=[],
        raise_on_empty=True,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=False,
        include_display_values=False,
        **get_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Extract date from events data

# %%
# parameters

extract_event_date_params = dict()

# %%
# call the task


extract_event_date = (
    extract_column_as_type.set_task_instance_id("extract_event_date")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_events_data,
        column_name="time",
        output_type="date",
        output_column_name="date",
        **extract_event_date_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index on events

# %%
# parameters

events_temporal_params = dict()

# %%
# call the task


events_temporal = (
    add_temporal_index.set_task_instance_id("events_temporal")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_event_date,
        time_col="date",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **events_temporal_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude specific events types from total events

# %%
# parameters

filter_events_params = dict()

# %%
# call the task


filter_events = (
    exclude_row_values.set_task_instance_id("filter_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=events_temporal,
        column="event_type",
        values=[
            "distancecountwildlife_rep",
            "distancecountpatrol_rep",
            "airstrip_operations",
        ],
        **filter_events_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate total events

# %%
# parameters

total_events_recorded_params = dict()

# %%
# call the task


total_events_recorded = (
    summarize_df.set_task_instance_id("total_events_recorded")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date"],
        summary_params=[
            {"display_name": "no_of_events", "aggregator": "nunique", "column": "id"}
        ],
        reset_index=True,
        df=filter_events,
        **total_events_recorded_params,
    )
    .call()
)


# %% [markdown]
# ## Add total row on total events recorded

# %%
# parameters

add_total_events_row_params = dict()

# %%
# call the task


add_total_events_row = (
    add_totals_row.set_task_instance_id("add_total_events_row")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["date"],
        label="Total",
        df=total_events_recorded,
        **add_total_events_row_params,
    )
    .call()
)


# %% [markdown]
# ## Persist total events df

# %%
# parameters

persist_tevents_df_params = dict()

# %%
# call the task


persist_tevents_df = (
    persist_df.set_task_instance_id("persist_tevents_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_total_events_row,
        filename="total_events_recorded_by_date",
        **persist_tevents_df_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate total events recorded by event type

# %%
# parameters

total_events_type_recorded_params = dict()

# %%
# call the task


total_events_type_recorded = (
    summarize_df.set_task_instance_id("total_events_type_recorded")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date", "event_type"],
        summary_params=[
            {"display_name": "no_of_events", "aggregator": "nunique", "column": "id"}
        ],
        reset_index=True,
        df=filter_events,
        **total_events_type_recorded_params,
    )
    .call()
)


# %% [markdown]
# ## Persist total events by event type df

# %%
# parameters

persist_summary_event_type_params = dict()

# %%
# call the task


persist_summary_event_type = (
    persist_df.set_task_instance_id("persist_summary_event_type")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=total_events_type_recorded,
        filename="total_events_recorded_by_type",
        **persist_summary_event_type_params,
    )
    .call()
)


# %% [markdown]
# ## Draw total events line chart

# %%
# parameters

draw_events_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_events_chart = (
    draw_line_chart.set_task_instance_id("draw_events_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        smoothing=None,
        dataframe=total_events_recorded,
        x_column="date",
        y_column="no_of_events",
        category_column=None,
        line_kwargs={"shape": "linear", "color": "lightsteelblue"},
        layout_kwargs={
            "title": None,
            "title_x": 0.01,
            "title_y": 0.95,
            "showlegend": False,
            "fontsize": 20,
            "fontcolor": "#2c3e50",
            "plot_bgcolor": "#f5f5f5",
            "xaxis": {
                "title": "Date",
                "tickformat": "%Y-%m-%d",
                "tickangle": -45,
                "rangemode": "auto",
            },
            "yaxis": {"title": "Number of events", "tickformat": ".1f"},
            "hovermode": "x unified",
        },
        **draw_events_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Total events chart as text

# %%
# parameters

persist_total_events_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_total_events = (
    persist_text.set_task_instance_id("persist_total_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_events_chart,
        filename="total_events_recorded.html",
        **persist_total_events_params,
    )
    .call()
)


# %% [markdown]
# ## Convert total events html to png

# %%
# parameters

convert_tevents_png_params = dict()

# %%
# call the task


convert_tevents_png = (
    html_to_png.set_task_instance_id("convert_tevents_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_total_events,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 10,
            "max_concurrent_pages": 1,
        },
        **convert_tevents_png_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get patrol information

# %%
# parameters

filter_patrol_info_events_params = dict()

# %%
# call the task


filter_patrol_info_events = (
    filter_df.set_task_instance_id("filter_patrol_info_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="patrol_info",
        df=events_temporal,
        reset_index=False,
        **filter_patrol_info_events_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_pi_values_params = dict()

# %%
# call the task


normalize_pi_values = (
    normalize_json_column.set_task_instance_id("normalize_pi_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_patrol_info_events,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_pi_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename patrol information columns

# %%
# parameters

rename_patrol_info_params = dict()

# %%
# call the task


rename_patrol_info = (
    map_columns.set_task_instance_id("rename_patrol_info")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "event_details__patrolinfomation_participants": "participants",
            "event_details__patrolinfomation_patrolpurpose": "purpose",
            "event_details__patrolinfomation_personwhoauthorised": "authorized_by",
            "event_details__patrolinfomation_transporttype": "transport_type",
            "patrols": "patrol_id",
        },
        df=normalize_pi_values,
        **rename_patrol_info_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol information Summary

# %%
# parameters

patrol_info_summary_params = dict()

# %%
# call the task


patrol_info_summary = (
    summarize_df.set_task_instance_id("patrol_info_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["purpose"],
        summary_params=[
            {"display_name": "no_of_patrols", "aggregator": "nunique", "column": "id"}
        ],
        reset_index=True,
        df=rename_patrol_info,
        **patrol_info_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Capitalize patrol text

# %%
# parameters

capitalize_patrol_text_params = dict()

# %%
# call the task


capitalize_patrol_text = (
    capitalize_text.set_task_instance_id("capitalize_patrol_text")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=patrol_info_summary, column="purpose", **capitalize_patrol_text_params)
    .call()
)


# %% [markdown]
# ## Add totals row in patrol info summary table

# %%
# parameters

include_pat_totals_params = dict()

# %%
# call the task


include_pat_totals = (
    add_totals_row.set_task_instance_id("include_pat_totals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["purpose"],
        label="Total",
        df=capitalize_patrol_text,
        **include_pat_totals_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol summary table

# %%
# parameters

persist_patrol_df_params = dict()

# %%
# call the task


persist_patrol_df = (
    persist_df.set_task_instance_id("persist_patrol_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        filename="patrol_purpose_summary",
        df=include_pat_totals,
        **persist_patrol_df_params,
    )
    .call()
)


# %% [markdown]
# ## Rename column values in participants

# %%
# parameters

rename_participants_params = dict()

# %%
# call the task


rename_participants = (
    map_name_values.set_task_instance_id("rename_participants")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=rename_patrol_info, column="participants", **rename_participants_params)
    .call()
)


# %% [markdown]
# ## Filter non empty values from patrols info

# %%
# parameters

filter_null_patrols_params = dict()

# %%
# call the task


filter_null_patrols = (
    filter_non_empty_values.set_task_instance_id("filter_null_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=rename_participants, column="patrol_id", **filter_null_patrols_params)
    .call()
)


# %% [markdown]
# ## Replace transport type nulls with unspecified

# %%
# parameters

replace_transport_unspecified_params = dict()

# %%
# call the task


replace_transport_unspecified = (
    replace_missing_with_label.set_task_instance_id("replace_transport_unspecified")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_null_patrols,
        columns=["transport_type"],
        label="unspecified",
        **replace_transport_unspecified_params,
    )
    .call()
)


# %% [markdown]
# ## Explode columns on patrols

# %%
# parameters

explode_patrol_columns_params = dict()

# %%
# call the task


explode_patrol_columns = (
    explode_multiple_columns.set_task_instance_id("explode_patrol_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=replace_transport_unspecified,
        columns=["patrol_id", "participants"],
        reset_index=True,
        **explode_patrol_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Get patrol values from patrol information

# %%
# parameters

get_patrols_from_info_params = dict()

# %%
# call the task


get_patrols_from_info = (
    get_patrol_values.set_task_instance_id("get_patrols_from_info")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        events_df=explode_patrol_columns,
        patrols_column="patrol_id",
        client=er_client_name,
        batch_size=15,
        **get_patrols_from_info_params,
    )
    .call()
)


# %% [markdown]
# ## Get patrol observations from patrol df

# %%
# parameters

get_patrol_obs_params = dict()

# %%
# call the task


get_patrol_obs = (
    custom_get_patrol_observations_from_patrols_df.set_task_instance_id(
        "get_patrol_obs"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        patrols_df=get_patrols_from_info,
        include_patrol_details=True,
        raise_on_empty=True,
        sub_page_size=150,
        **get_patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Drop values from patrol information df

# %%
# parameters

drop_values_patrol_info_params = dict()

# %%
# call the task


drop_values_patrol_info = (
    map_columns.set_task_instance_id("drop_values_patrol_info")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=["geometry", "reported_by", "index", "serial_number"],
        retain_columns=[],
        rename_columns={
            "authorized_by": "authorized_by",
            "event_details__updates": "updates",
        },
        df=explode_patrol_columns,
        **drop_values_patrol_info_params,
    )
    .call()
)


# %% [markdown]
# ## Merge dataframes

# %%
# parameters

merge_patrol_events_obs_params = dict()

# %%
# call the task


merge_patrol_events_obs = (
    merge_dataframes.set_task_instance_id("merge_patrol_events_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left_df=get_patrol_obs,
        right_df=drop_values_patrol_info,
        on="patrol_id",
        how="left",
        preserve_left_index=True,
        **merge_patrol_events_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Transform observations to relocations

# %%
# parameters

obs_relocs_params = dict()

# %%
# call the task


obs_relocs = (
    process_relocations.set_task_instance_id("obs_relocs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        observations=merge_patrol_events_obs,
        relocs_columns=[
            "extra__id",
            "extra__created_at",
            "extra__subject_id",
            "geometry",
            "groupby_col",
            "fixtime",
            "junk_status",
            "patrol_id",
            "patrol_title",
            "patrol_serial_number",
            "patrol_start_time",
            "patrol_end_time",
            "patrol_type",
            "patrol_status",
            "patrol_subject",
            "patrol_type__value",
            "participants",
            "purpose",
            "transport_type",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **obs_relocs_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol observations as relocations

# %%
# parameters

persist_relocs_params = dict()

# %%
# call the task


persist_relocs = (
    persist_df.set_task_instance_id("persist_relocs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="geoparquet",
        filename="patrol_relocations",
        df=obs_relocs,
        **persist_relocs_params,
    )
    .call()
)


# %% [markdown]
# ## Filter foot patrol observations

# %%
# parameters

filter_foot_patrols_params = dict()

# %%
# call the task


filter_foot_patrols = (
    filter_df.set_task_instance_id("filter_foot_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="transport_type",
        op="equal",
        value="foot",
        df=obs_relocs,
        reset_index=False,
        **filter_foot_patrols_params,
    )
    .call()
)


# %% [markdown]
# ## Filter vehicle patrol observations

# %%
# parameters

filter_vehicle_patrols_params = dict()

# %%
# call the task


filter_vehicle_patrols = (
    filter_df.set_task_instance_id("filter_vehicle_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="transport_type",
        op="equal",
        value="vehicle",
        df=obs_relocs,
        reset_index=False,
        **filter_vehicle_patrols_params,
    )
    .call()
)


# %% [markdown]
# ## Filter motorbike patrol observations

# %%
# parameters

filter_motor_patrols_params = dict()

# %%
# call the task


filter_motor_patrols = (
    filter_df.set_task_instance_id("filter_motor_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="transport_type",
        op="equal",
        value="motorbike",
        df=obs_relocs,
        reset_index=False,
        **filter_motor_patrols_params,
    )
    .call()
)


# %% [markdown]
# ## Filter unspecified patrol observations

# %%
# parameters

filter_unspecified_patrols_params = dict()

# %%
# call the task


filter_unspecified_patrols = (
    filter_df.set_task_instance_id("filter_unspecified_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="transport_type",
        op="equal",
        value="unspecified",
        df=obs_relocs,
        reset_index=False,
        **filter_unspecified_patrols_params,
    )
    .call()
)


# %% [markdown]
# ## Convert vehicle relocations to trajectories

# %%
# parameters

vehicle_trajs_params = dict()

# %%
# call the task


vehicle_trajs = (
    relocations_to_trajectory.set_task_instance_id("vehicle_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        relocations=filter_vehicle_patrols,
        trajectory_segment_filter={
            "min_length_meters": 0.35,
            "max_length_meters": 5000.0,
            "max_time_secs": 18000.0,
            "min_time_secs": 1.0,
            "max_speed_kmhr": 100.0,
            "min_speed_kmhr": 10.0,
        },
        **vehicle_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Convert motorbike relocations to trajectories

# %%
# parameters

motor_trajs_params = dict()

# %%
# call the task


motor_trajs = (
    relocations_to_trajectory.set_task_instance_id("motor_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        relocations=filter_motor_patrols,
        trajectory_segment_filter={
            "min_length_meters": 0.35,
            "max_length_meters": 5000.0,
            "max_time_secs": 18000.0,
            "min_time_secs": 1.0,
            "max_speed_kmhr": 100.0,
            "min_speed_kmhr": 10.0,
        },
        **motor_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Convert foot relocations to trajectories

# %%
# parameters

foot_trajs_params = dict()

# %%
# call the task


foot_trajs = (
    relocations_to_trajectory.set_task_instance_id("foot_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        relocations=filter_foot_patrols,
        trajectory_segment_filter={
            "min_length_meters": 0.001,
            "max_length_meters": 5000.0,
            "max_time_secs": 14400.0,
            "min_time_secs": 1.0,
            "max_speed_kmhr": 9.0,
            "min_speed_kmhr": 0.5,
        },
        **foot_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index to foot trajs

# %%
# parameters

temporal_foot_traj_params = dict()

# %%
# call the task


temporal_foot_traj = (
    add_temporal_index.set_task_instance_id("temporal_foot_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=foot_trajs,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **temporal_foot_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index to vehicle trajs

# %%
# parameters

temporal_vehicle_traj_params = dict()

# %%
# call the task


temporal_vehicle_traj = (
    add_temporal_index.set_task_instance_id("temporal_vehicle_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=vehicle_trajs,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **temporal_vehicle_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index to motorbike trajs

# %%
# parameters

temporal_motor_traj_params = dict()

# %%
# call the task


temporal_motor_traj = (
    add_temporal_index.set_task_instance_id("temporal_motor_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=motor_trajs,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **temporal_motor_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Rename foot traj columns

# %%
# parameters

rename_foot_trajs_params = dict()

# %%
# call the task


rename_foot_trajs = (
    map_columns.set_task_instance_id("rename_foot_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=["heading", "extra__created_at", "extra__id"],
        retain_columns=[],
        rename_columns={
            "extra__patrol_start_time": "patrol_start_time",
            "extra__patrol_end_time": "patrol_end_time",
            "extra__patrol_id": "patrol_id",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "patrol_subject_name",
            "extra__patrol_title": "patrol_title",
            "extra__patrol_type": "patrol_type_id",
            "extra__patrol_type__value": "patrol_type_value",
            "extra__subject_id": "subject_id",
        },
        df=temporal_foot_traj,
        **rename_foot_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Rename vehicle traj columns

# %%
# parameters

rename_vehicle_trajs_params = dict()

# %%
# call the task


rename_vehicle_trajs = (
    map_columns.set_task_instance_id("rename_vehicle_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=["heading", "extra__created_at", "extra__id"],
        retain_columns=[],
        rename_columns={
            "extra__patrol_start_time": "patrol_start_time",
            "extra__patrol_end_time": "patrol_end_time",
            "extra__patrol_id": "patrol_id",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "patrol_subject_name",
            "extra__patrol_title": "patrol_title",
            "extra__patrol_type": "patrol_type_id",
            "extra__patrol_type__value": "patrol_type_value",
            "extra__subject_id": "subject_id",
        },
        df=temporal_vehicle_traj,
        **rename_vehicle_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Rename motor traj columns

# %%
# parameters

rename_motor_trajs_params = dict()

# %%
# call the task


rename_motor_trajs = (
    map_columns.set_task_instance_id("rename_motor_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=["heading", "extra__created_at", "extra__id"],
        retain_columns=[],
        rename_columns={
            "extra__patrol_start_time": "patrol_start_time",
            "extra__patrol_end_time": "patrol_end_time",
            "extra__patrol_id": "patrol_id",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "patrol_subject_name",
            "extra__patrol_title": "patrol_title",
            "extra__patrol_type": "patrol_type_id",
            "extra__patrol_type__value": "patrol_type_value",
            "extra__subject_id": "subject_id",
        },
        df=temporal_motor_traj,
        **rename_motor_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize foot patrol metrics

# %%
# parameters

foot_patrol_metrics_params = dict()

# %%
# call the task


foot_patrol_metrics = (
    summarize_df.set_task_instance_id("foot_patrol_metrics")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["patrol_type_value"],
        summary_params=[
            {
                "display_name": "no_of_patrols",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "distance_km",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "duration_hrs",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
            },
            {
                "display_name": "average_speed",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
        ],
        reset_index=True,
        df=rename_foot_trajs,
        **foot_patrol_metrics_params,
    )
    .call()
)


# %% [markdown]
# ## Add totals row to foot patrol metrics

# %%
# parameters

add_fp_metrics_totals_params = dict()

# %%
# call the task


add_fp_metrics_totals = (
    add_totals_row.set_task_instance_id("add_fp_metrics_totals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["patrol_type_value"],
        label="Total",
        df=foot_patrol_metrics,
        **add_fp_metrics_totals_params,
    )
    .call()
)


# %% [markdown]
# ## Persist foot patrol metrics

# %%
# parameters

persist_foot_df_params = dict()

# %%
# call the task


persist_foot_df = (
    persist_df.set_task_instance_id("persist_foot_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        filename="foot_patrol_efforts",
        df=add_fp_metrics_totals,
        **persist_foot_df_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to foot patrols

# %%
# parameters

apply_footp_colormap_params = dict()

# %%
# call the task


apply_footp_colormap = (
    apply_color_map.set_task_instance_id("apply_footp_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="patrol_type_value",
        output_column_name="foot_patrol_colors",
        colormap="tab20",
        df=rename_foot_trajs,
        **apply_footp_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist foot patrols as geojson

# %%
# parameters

persist_foot_geojson_params = dict()

# %%
# call the task


persist_foot_geojson = (
    gdf_to_geojson.set_task_instance_id("persist_foot_geojson")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=apply_footp_colormap,
        filename="foot_patrol_trajectories",
        **persist_foot_geojson_params,
    )
    .call()
)


# %% [markdown]
# ## Generate foot patrol layers

# %%
# parameters

generate_foot_layers_params = dict()

# %%
# call the task


generate_foot_layers = (
    create_geojson_layer.set_task_instance_id("generate_foot_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": True,
            "stroked": True,
            "extruded": False,
            "wireframe": False,
            "get_fill_color": "foot_patrol_colors",
            "get_line_color": "foot_patrol_colors",
            "opacity": 0.55,
            "get_line_width": 1.55,
            "get_elevation": 0,
            "get_point_radius": 1,
            "line_width_units": "pixels",
            "line_width_scale": 1,
            "line_width_min_pixels": 1,
            "line_width_max_pixels": 5,
        },
        legend={
            "title": "Patrol Type",
            "label_column": "patrol_type_value",
            "color_column": "foot_patrol_colors",
            "sort": "ascending",
        },
        geodataframe=apply_footp_colormap,
        data_url=persist_foot_geojson,
        **generate_foot_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine styled layers with foot layers

# %%
# parameters

combine_foot_layers_params = dict()

# %%
# call the task


combine_foot_layers = (
    combine_deckgl_map_layers.set_task_instance_id("combine_foot_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_conservancy_boundaries,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_foot_layers,
        **combine_foot_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Global map zoom value

# %%
# parameters

global_zoom_value_params = dict()

# %%
# call the task


global_zoom_value = (
    view_state_deck_gdf.set_task_instance_id("global_zoom_value")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(pitch=0, bearing=0, gdf=overall_grazing_zones, **global_zoom_value_params)
    .call()
)


# %% [markdown]
# ## Draw foot patrols map

# %%
# parameters

draw_foot_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_foot_map = (
    draw_map.set_task_instance_id("draw_foot_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_foot_layers,
        view_state=global_zoom_value,
        **draw_foot_map_params,
    )
    .call()
)


# %% [markdown]
# ## Rewrite foot patrols file urls

# %%
# parameters

rewrite_foot_patrol_urls_params = dict()

# %%
# call the task


rewrite_foot_patrol_urls = (
    rewrite_file_urls_for_screenshots.set_task_instance_id("rewrite_foot_patrol_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html=draw_foot_map,
        file_urls=[persist_foot_geojson],
        **rewrite_foot_patrol_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Persist foot patrols map HTML

# %%
# parameters

persist_foot_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_foot_urls = (
    persist_text.set_task_instance_id("persist_foot_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=rewrite_foot_patrol_urls,
        filename="foot_patrols_map.html",
        **persist_foot_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert foot patrol map to png

# %%
# parameters

convert_foot_png_params = dict()

# %%
# call the task


convert_foot_png = (
    html_to_png.set_task_instance_id("convert_foot_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html_path=persist_foot_urls,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
            "serve_local_files": True,
        },
        **convert_foot_png_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize vehicle patrol metrics

# %%
# parameters

vehicle_patrol_metrics_params = dict()

# %%
# call the task


vehicle_patrol_metrics = (
    summarize_df.set_task_instance_id("vehicle_patrol_metrics")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["patrol_type_value"],
        summary_params=[
            {
                "display_name": "no_of_patrols",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "distance_km",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "duration_hrs",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
            },
            {
                "display_name": "average_speed",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
        ],
        reset_index=True,
        df=rename_vehicle_trajs,
        **vehicle_patrol_metrics_params,
    )
    .call()
)


# %% [markdown]
# ## Add totals row to vehicle patrols summary

# %%
# parameters

add_vh_metrics_totals_params = dict()

# %%
# call the task


add_vh_metrics_totals = (
    add_totals_row.set_task_instance_id("add_vh_metrics_totals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["patrol_type_value"],
        label="Total",
        df=vehicle_patrol_metrics,
        **add_vh_metrics_totals_params,
    )
    .call()
)


# %% [markdown]
# ## Persist vehicle patrol metrics

# %%
# parameters

persist_vehicle_df_params = dict()

# %%
# call the task


persist_vehicle_df = (
    persist_df.set_task_instance_id("persist_vehicle_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_vh_metrics_totals,
        filename="vehicle_patrol_efforts",
        **persist_vehicle_df_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to vehicle patrols

# %%
# parameters

apply_vehicle_colormap_params = dict()

# %%
# call the task


apply_vehicle_colormap = (
    apply_color_map.set_task_instance_id("apply_vehicle_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="patrol_type_value",
        output_column_name="vehicle_patrol_colors",
        colormap="tab20",
        df=rename_vehicle_trajs,
        **apply_vehicle_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist vehicle patrols as geojson

# %%
# parameters

persist_vehicle_geojson_params = dict()

# %%
# call the task


persist_vehicle_geojson = (
    gdf_to_geojson.set_task_instance_id("persist_vehicle_geojson")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=apply_vehicle_colormap,
        filename="vehicle_patrol_trajectories",
        **persist_vehicle_geojson_params,
    )
    .call()
)


# %% [markdown]
# ## Generate vehicle patrol layers

# %%
# parameters

generate_vehicle_layers_params = dict()

# %%
# call the task


generate_vehicle_layers = (
    create_geojson_layer.set_task_instance_id("generate_vehicle_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": True,
            "stroked": True,
            "extruded": False,
            "wireframe": False,
            "get_fill_color": "vehicle_patrol_colors",
            "get_line_color": "vehicle_patrol_colors",
            "opacity": 0.55,
            "get_line_width": 1.55,
            "get_elevation": 0,
            "get_point_radius": 1,
            "line_width_units": "pixels",
            "line_width_scale": 1,
            "line_width_min_pixels": 1,
            "line_width_max_pixels": 5,
        },
        legend={
            "title": "Patrol Type",
            "label_column": "patrol_type_value",
            "color_column": "vehicle_patrol_colors",
            "sort": "ascending",
        },
        geodataframe=apply_vehicle_colormap,
        data_url=persist_vehicle_geojson,
        **generate_vehicle_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine styled layers with vehicle layers

# %%
# parameters

combine_vehicle_layers_params = dict()

# %%
# call the task


combine_vehicle_layers = (
    combine_deckgl_map_layers.set_task_instance_id("combine_vehicle_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_conservancy_boundaries,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_vehicle_layers,
        **combine_vehicle_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw vehicle patrols map

# %%
# parameters

draw_vehicle_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_vehicle_map = (
    draw_map.set_task_instance_id("draw_vehicle_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_vehicle_layers,
        view_state=global_zoom_value,
        **draw_vehicle_map_params,
    )
    .call()
)


# %% [markdown]
# ## Rewrite vehicle patrols file urls

# %%
# parameters

rewrite_vehicle_patrol_urls_params = dict()

# %%
# call the task


rewrite_vehicle_patrol_urls = (
    rewrite_file_urls_for_screenshots.set_task_instance_id(
        "rewrite_vehicle_patrol_urls"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html=draw_vehicle_map,
        file_urls=[persist_vehicle_geojson],
        **rewrite_vehicle_patrol_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Persist vehicle patrols map HTML

# %%
# parameters

persist_vehicle_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_vehicle_urls = (
    persist_text.set_task_instance_id("persist_vehicle_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=rewrite_vehicle_patrol_urls,
        filename="vehicle_patrols_map.html",
        **persist_vehicle_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert vehicle patrol map to png

# %%
# parameters

convert_vehicle_png_params = dict()

# %%
# call the task


convert_vehicle_png = (
    html_to_png.set_task_instance_id("convert_vehicle_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_vehicle_urls,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
            "serve_local_files": True,
        },
        **convert_vehicle_png_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize motorbike patrol metrics

# %%
# parameters

motor_patrol_metrics_params = dict()

# %%
# call the task


motor_patrol_metrics = (
    summarize_df.set_task_instance_id("motor_patrol_metrics")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["patrol_type_value"],
        summary_params=[
            {
                "display_name": "no_of_patrols",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "distance_km",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "duration_hrs",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
            },
            {
                "display_name": "average_speed",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
        ],
        reset_index=True,
        df=rename_motor_trajs,
        **motor_patrol_metrics_params,
    )
    .call()
)


# %% [markdown]
# ## Add totals row to motorbike patrols

# %%
# parameters

add_mb_metrics_totals_params = dict()

# %%
# call the task


add_mb_metrics_totals = (
    add_totals_row.set_task_instance_id("add_mb_metrics_totals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["patrol_type_value"],
        label="Total",
        df=motor_patrol_metrics,
        **add_mb_metrics_totals_params,
    )
    .call()
)


# %% [markdown]
# ## Persist motorbike patrol metrics

# %%
# parameters

persist_motor_df_params = dict()

# %%
# call the task


persist_motor_df = (
    persist_df.set_task_instance_id("persist_motor_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_mb_metrics_totals,
        filename="motorbike_patrol_efforts",
        **persist_motor_df_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to motor patrols

# %%
# parameters

apply_motor_colormap_params = dict()

# %%
# call the task


apply_motor_colormap = (
    apply_color_map.set_task_instance_id("apply_motor_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="patrol_type_value",
        output_column_name="motor_patrol_colors",
        colormap="tab20",
        df=rename_motor_trajs,
        **apply_motor_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist motor patrols as geojson

# %%
# parameters

persist_motor_geojson_params = dict()

# %%
# call the task


persist_motor_geojson = (
    gdf_to_geojson.set_task_instance_id("persist_motor_geojson")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=apply_motor_colormap,
        filename="motor_patrol_trajectories",
        **persist_motor_geojson_params,
    )
    .call()
)


# %% [markdown]
# ## Generate motor patrol layers

# %%
# parameters

generate_motor_layers_params = dict()

# %%
# call the task


generate_motor_layers = (
    create_geojson_layer.set_task_instance_id("generate_motor_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": True,
            "stroked": True,
            "extruded": False,
            "wireframe": False,
            "get_fill_color": "motor_patrol_colors",
            "get_line_color": "motor_patrol_colors",
            "opacity": 0.55,
            "get_line_width": 1.55,
            "get_elevation": 0,
            "get_point_radius": 1,
            "line_width_units": "pixels",
            "line_width_scale": 1,
            "line_width_min_pixels": 1,
            "line_width_max_pixels": 5,
        },
        legend={
            "title": "Patrol Type",
            "label_column": "patrol_type_value",
            "color_column": "motor_patrol_colors",
            "sort": "ascending",
        },
        geodataframe=apply_motor_colormap,
        data_url=persist_motor_geojson,
        **generate_motor_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine styled layers with motorbike layers

# %%
# parameters

combine_motor_layers_params = dict()

# %%
# call the task


combine_motor_layers = (
    combine_deckgl_map_layers.set_task_instance_id("combine_motor_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_conservancy_boundaries,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_motor_layers,
        **combine_motor_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw motor patrols map

# %%
# parameters

draw_motor_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_motor_map = (
    draw_map.set_task_instance_id("draw_motor_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_motor_layers,
        view_state=global_zoom_value,
        **draw_motor_map_params,
    )
    .call()
)


# %% [markdown]
# ## Rewrite motor patrols file urls

# %%
# parameters

rewrite_motor_patrol_urls_params = dict()

# %%
# call the task


rewrite_motor_patrol_urls = (
    rewrite_file_urls_for_screenshots.set_task_instance_id("rewrite_motor_patrol_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html=draw_motor_map,
        file_urls=[persist_motor_geojson],
        **rewrite_motor_patrol_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Persist motor patrols map HTML

# %%
# parameters

persist_motor_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_motor_urls = (
    persist_text.set_task_instance_id("persist_motor_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=rewrite_motor_patrol_urls,
        filename="motorbike_patrols_map.html",
        **persist_motor_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert motor patrol map to png

# %%
# parameters

convert_motor_png_params = dict()

# %%
# call the task


convert_motor_png = (
    html_to_png.set_task_instance_id("convert_motor_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_motor_urls,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
            "serve_local_files": True,
        },
        **convert_motor_png_params,
    )
    .call()
)


# %% [markdown]
# ## Merge motorbike, vehicle and foot patrol trajectories

# %%
# parameters

merge_trajs_params = dict()

# %%
# call the task


merge_trajs = (
    merge_multiple_df.set_task_instance_id("merge_trajs")
    .handle_errors()
    .with_tracing()
    .partial(
        list_df=[foot_trajs, vehicle_trajs, motor_trajs],
        ignore_index=True,
        sort=False,
        **merge_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Rename merged trajectory columns

# %%
# parameters

rename_combined_trajs_params = dict()

# %%
# call the task


rename_combined_trajs = (
    map_columns.set_task_instance_id("rename_combined_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=["heading", "extra__created_at", "extra__id"],
        retain_columns=[],
        rename_columns={
            "extra__patrol_start_time": "patrol_start_time",
            "extra__patrol_end_time": "patrol_end_time",
            "extra__patrol_id": "patrol_id",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "patrol_subject_name",
            "extra__patrol_title": "patrol_title",
            "extra__patrol_type": "patrol_type_id",
            "extra__patrol_type__value": "patrol_type_value",
            "extra__subject_id": "subject_id",
            "extra__participants": "participants",
        },
        df=merge_trajs,
        **rename_combined_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Persist combined trajectories data

# %%
# parameters

persist_trajectories_data_params = dict()

# %%
# call the task


persist_trajectories_data = (
    persist_df.set_task_instance_id("persist_trajectories_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="geoparquet",
        df=rename_combined_trajs,
        filename="patrol_trajectories",
        **persist_trajectories_data_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize overall ranger patrol metrics

# %%
# parameters

ranger_patrol_metrics_params = dict()

# %%
# call the task


ranger_patrol_metrics = (
    summarize_df.set_task_instance_id("ranger_patrol_metrics")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["participants"],
        summary_params=[
            {
                "display_name": "no_of_patrols",
                "aggregator": "nunique",
                "column": "patrol_id",
                "decimal_places": 0,
            },
            {
                "display_name": "distance_km",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
                "decimal_places": 2,
            },
            {
                "display_name": "duration_hrs",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 2,
            },
        ],
        reset_index=True,
        df=rename_combined_trajs,
        **ranger_patrol_metrics_params,
    )
    .call()
)


# %% [markdown]
# ## Replace nulls with unspecified

# %%
# parameters

replace_ranger_nulls_params = dict()

# %%
# call the task


replace_ranger_nulls = (
    replace_missing_with_label.set_task_instance_id("replace_ranger_nulls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=ranger_patrol_metrics,
        columns=["participants"],
        label="Unspecified",
        **replace_ranger_nulls_params,
    )
    .call()
)


# %% [markdown]
# ## Add totals row to overall patrol metrics

# %%
# parameters

add_ranger_metrics_totals_params = dict()

# %%
# call the task


add_ranger_metrics_totals = (
    add_totals_row.set_task_instance_id("add_ranger_metrics_totals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["participants"],
        label="Total",
        df=replace_ranger_nulls,
        **add_ranger_metrics_totals_params,
    )
    .call()
)


# %% [markdown]
# ## Persist total patrol coverage

# %%
# parameters

persist_total_df_params = dict()

# %%
# call the task


persist_total_df = (
    persist_df.set_task_instance_id("persist_total_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_ranger_metrics_totals,
        filename="overall_patrol_efforts",
        **persist_total_df_params,
    )
    .call()
)


# %% [markdown]
# ## Compute patrol visits

# %%
# parameters

patrol_grid_visits_params = dict()

# %%
# call the task


patrol_grid_visits = (
    create_patrol_coverage_grid.set_task_instance_id("patrol_grid_visits")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        grid_cell_size=1000, trajs=rename_combined_trajs, **patrol_grid_visits_params
    )
    .call()
)


# %% [markdown]
# ## Apply bin classification on grids

# %%
# parameters

apply_classification_grid_params = dict()

# %%
# call the task


apply_classification_grid = (
    apply_classification.set_task_instance_id("apply_classification_grid")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="unique_patrol_count",
        output_column_name="density_bins",
        label_options={"label_ranges": False, "label_decimals": 1},
        classification_options={"k": 5, "scheme": "equal_interval"},
        df=patrol_grid_visits,
        **apply_classification_grid_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to patrol grid visits

# %%
# parameters

apply_grid_colormap_params = dict()

# %%
# call the task


apply_grid_colormap = (
    apply_color_map.set_task_instance_id("apply_grid_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="density_bins",
        colormap="RdYlGn_r",
        output_column_name="density_colors",
        df=apply_classification_grid,
        **apply_grid_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrol visit grid layers

# %%
# parameters

generate_grid_layers_params = dict()

# %%
# call the task


generate_grid_layers = (
    create_geojson_layer.set_task_instance_id("generate_grid_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": True,
            "stroked": True,
            "extruded": False,
            "wireframe": False,
            "get_fill_color": "density_colors",
            "get_line_color": [0, 0, 0],
            "opacity": 0.75,
            "get_line_width": 0.85,
            "get_elevation": 0,
            "get_point_radius": 1,
            "line_width_units": "pixels",
            "line_width_scale": 1,
            "line_width_min_pixels": 1,
            "line_width_max_pixels": 5,
        },
        legend={
            "title": "Visits",
            "label_column": "density_bins",
            "color_column": "density_colors",
        },
        geodataframe=apply_grid_colormap,
        data_url=None,
        **generate_grid_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine styled layers with patrol coverage

# %%
# parameters

combine_grid_layers_params = dict()

# %%
# call the task


combine_grid_layers = (
    combine_deckgl_map_layers.set_task_instance_id("combine_grid_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_conservancy_boundaries,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_grid_layers,
        **combine_grid_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrol coverage map

# %%
# parameters

draw_grid_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_grid_map = (
    draw_map.set_task_instance_id("draw_grid_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_grid_layers,
        view_state=global_zoom_value,
        **draw_grid_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol coverage map HTML

# %%
# parameters

persist_grid_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_grid_urls = (
    persist_text.set_task_instance_id("persist_grid_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_grid_map,
        filename="patrol_coverage_map.html",
        **persist_grid_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert grid map to png

# %%
# parameters

convert_grid_png_params = dict()

# %%
# call the task


convert_grid_png = (
    html_to_png.set_task_instance_id("convert_grid_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_grid_urls,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
        },
        **convert_grid_png_params,
    )
    .call()
)


# %% [markdown]
# ## Compute patrol occupancy

# %%
# parameters

compute_patrol_occupancy_params = dict()

# %%
# call the task


compute_patrol_occupancy = (
    compute_occupancy.set_task_instance_id("compute_patrol_occupancy")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        coverage_grid_gdf=patrol_grid_visits,
        regions_gdf=conservancy_gdf,
        crs="epsg:4326",
        **compute_patrol_occupancy_params,
    )
    .call()
)


# %% [markdown]
# ## Round off values to two decimal places

# %%
# parameters

round_off_patrol_params = dict()

# %%
# call the task


round_off_patrol = (
    round_values.set_task_instance_id("round_off_patrol")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=compute_patrol_occupancy,
        column="occupancy_percentage",
        decimals=2,
        **round_off_patrol_params,
    )
    .call()
)


# %% [markdown]
# ## Persist occupancy df

# %%
# parameters

persist_occupancy_df_params = dict()

# %%
# call the task


persist_occupancy_df = (
    persist_df.set_task_instance_id("persist_occupancy_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=round_off_patrol,
        filename="patrol_coverage",
        **persist_occupancy_df_params,
    )
    .call()
)


# %% [markdown]
# ## MNC event report dashboard

# %%
# parameters

mnc_events_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


mnc_events_dashboard = (
    gather_dashboard.set_task_instance_id("mnc_events_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **mnc_events_dashboard_params,
    )
    .call()
)
