# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import compute_occupancy as compute_occupancy
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_patrol_coverage_grid as create_patrol_coverage_grid,
)
from ecoscope_workflows_ext_mnc.tasks import (
    custom_get_patrol_observations_from_patrols_df as custom_get_patrol_observations_from_patrols_df,
)
from ecoscope_workflows_ext_mnc.tasks import (
    explode_multiple_columns as explode_multiple_columns,
)
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import (
    filter_non_empty_values as filter_non_empty_values,
)
from ecoscope_workflows_ext_mnc.tasks import get_patrol_values as get_patrol_values
from ecoscope_workflows_ext_mnc.tasks import map_name_values as map_name_values
from ecoscope_workflows_ext_mnc.tasks import merge_dataframes as merge_dataframes
from ecoscope_workflows_ext_mnc.tasks import merge_multiple_df as merge_multiple_df
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import round_values as round_values
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type_1,
)
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type_1
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1,
                    "max_zoom": 20,
                }
            ],
            **(params_dict.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_mnc_gpkg")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    download_mnc_parcels = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("download_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("download_mnc_parcels") or {}),
        )
        .call()
    )

    load_comm_shp = (
        load_df.validate()
        .set_task_instance_id("load_comm_shp")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=persist_mnc_gpkg,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_comm_shp") or {}),
        )
        .call()
    )

    split_gdf_by_zone = (
        split_gdf_by_column.validate()
        .set_task_instance_id("split_gdf_by_zone")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=load_comm_shp,
            column="grazing_zone",
            **(params_dict.get("split_gdf_by_zone") or {}),
        )
        .call()
    )

    annotate_comm_gdf_dict = (
        annotate_gdf_dict_with_geom_type_1.validate()
        .set_task_instance_id("annotate_comm_gdf_dict")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            **(params_dict.get("annotate_comm_gdf_dict") or {}),
        )
        .call()
    )

    create_mnc_styled_layers = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_mnc_styled_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [169, 169, 169],
                    "get_line_color": [169, 169, 169],
                    "get_line_width": 4.0,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.95,
                },
                "Conservancy Herd Zone": {
                    "extruded": False,
                    "get_fill_color": [173, 255, 47],
                    "get_line_color": [173, 255, 47],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 1": {
                    "extruded": False,
                    "get_fill_color": [85, 107, 47],
                    "get_line_color": [85, 107, 47],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 2": {
                    "extruded": False,
                    "get_fill_color": [0, 139, 139],
                    "get_line_color": [0, 139, 139],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 3": {
                    "extruded": False,
                    "get_fill_color": [0, 100, 0],
                    "get_line_color": [0, 100, 0],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 4": {
                    "extruded": False,
                    "get_fill_color": [143, 188, 139],
                    "get_line_color": [143, 188, 139],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
            },
            legends={
                "title": "Legend",
                "values": [
                    {"label": "Conservancy", "color": "#a9a9a9"},
                    {"label": "Conservancy Herd Zone", "color": "#adff2f"},
                    {"label": "Grazing Zone 1", "color": "#556b2f"},
                    {"label": "Grazing Zone 2", "color": "#008b8b"},
                    {"label": "Grazing Zone 3", "color": "#006400"},
                    {"label": "Grazing Zone 4", "color": "#8fbc8b"},
                ],
            },
            **(params_dict.get("create_mnc_styled_layers") or {}),
        )
        .call()
    )

    create_conservancy_boundaries = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [169, 169, 169],
                    "get_line_color": [169, 169, 169],
                    "get_line_width": 4.0,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.95,
                }
            },
            legends={
                "title": "Legend",
                "values": [{"label": "Boundaries", "color": "#a9a9a9"}],
            },
            **(params_dict.get("create_conservancy_boundaries") or {}),
        )
        .call()
    )

    conservancy_gdf = (
        create_gdf_from_dict.validate()
        .set_task_instance_id("conservancy_gdf")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            key="Conservancy",
            **(params_dict.get("conservancy_gdf") or {}),
        )
        .call()
    )

    overall_grazing_zones = (
        filter_df.validate()
        .set_task_instance_id("overall_grazing_zones")
        .handle_errors()
        .with_tracing()
        .partial(
            column_name="grazing_zone",
            op="ne",
            value="Conservancy",
            df=load_comm_shp,
            reset_index=False,
            **(params_dict.get("overall_grazing_zones") or {}),
        )
        .call()
    )

    conservancy_text_layer = (
        create_custom_text_layer.validate()
        .set_task_instance_id("conservancy_text_layer")
        .handle_errors()
        .with_tracing()
        .partial(
            geodataframe=conservancy_gdf,
            layer_style={
                "get_text": "name",
                "get_color": [0, 0, 0, 255],
                "get_size": 1500,
                "size_units": "meters",
                "size_min_pixels": 70,
                "size_max_pixels": 100,
                "size_scale": 2.25,
                "font_family": "Calibri",
                "font_weight": "700",
                "get_text_anchor": "middle",
                "get_alignment_baseline": "center",
                "billboard": True,
                "background_padding": [4, 8],
                "pickable": True,
                "auto_highlight": False,
            },
            use_centroid=True,
            legend=None,
            **(params_dict.get("conservancy_text_layer") or {}),
        )
        .call()
    )

    load_mnc_parcels = (
        load_df.validate()
        .set_task_instance_id("load_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=download_mnc_parcels,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_mnc_parcels") or {}),
        )
        .call()
    )

    assign_mnc_geom = (
        get_gdf_geom_type_1.validate()
        .set_task_instance_id("assign_mnc_geom")
        .handle_errors()
        .with_tracing()
        .partial(gdf=load_mnc_parcels, **(params_dict.get("assign_mnc_geom") or {}))
        .call()
    )

    create_mnc_parcels_layers = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("create_mnc_parcels_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=assign_mnc_geom,
            style={
                "extruded": False,
                "get_fill_color": [189, 183, 107],
                "get_line_color": [189, 183, 107],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            legend={"title": "", "values": [{"label": "Parcels", "color": "#bdb76b"}]},
            **(params_dict.get("create_mnc_parcels_layers") or {}),
        )
        .call()
    )

    get_events_data = (
        get_events.validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        add_temporal_index.validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_temporal") or {}),
        )
        .call()
    )

    filter_events = (
        exclude_row_values.validate()
        .set_task_instance_id("filter_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column="event_type",
            values=[
                "distancecountwildlife_rep",
                "distancecountpatrol_rep",
                "airstrip_operations",
            ],
            **(params_dict.get("filter_events") or {}),
        )
        .call()
    )

    total_events_recorded = (
        summarize_df.validate()
        .set_task_instance_id("total_events_recorded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=filter_events,
            **(params_dict.get("total_events_recorded") or {}),
        )
        .call()
    )

    add_total_events_row = (
        add_totals_row.validate()
        .set_task_instance_id("add_total_events_row")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["date"],
            label="Total",
            df=total_events_recorded,
            **(params_dict.get("add_total_events_row") or {}),
        )
        .call()
    )

    persist_tevents_df = (
        persist_df.validate()
        .set_task_instance_id("persist_tevents_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_total_events_row,
            filename="total_events_recorded_by_date",
            **(params_dict.get("persist_tevents_df") or {}),
        )
        .call()
    )

    total_events_type_recorded = (
        summarize_df.validate()
        .set_task_instance_id("total_events_type_recorded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date", "event_type"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=filter_events,
            **(params_dict.get("total_events_type_recorded") or {}),
        )
        .call()
    )

    persist_summary_event_type = (
        persist_df.validate()
        .set_task_instance_id("persist_summary_event_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=total_events_type_recorded,
            filename="total_events_recorded_by_type",
            **(params_dict.get("persist_summary_event_type") or {}),
        )
        .call()
    )

    draw_events_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("draw_events_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=total_events_recorded,
            x_column="date",
            y_column="no_of_events",
            category_column=None,
            line_kwargs={"shape": "linear", "color": "lightsteelblue"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": False,
                "fontsize": 20,
                "fontcolor": "#2c3e50",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Number of events", "tickformat": ".1f"},
                "hovermode": "x unified",
            },
            **(params_dict.get("draw_events_chart") or {}),
        )
        .call()
    )

    persist_total_events = (
        persist_text.validate()
        .set_task_instance_id("persist_total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_events_chart,
            filename="total_events_recorded.html",
            **(params_dict.get("persist_total_events") or {}),
        )
        .call()
    )

    filter_patrol_info_events = (
        filter_df.validate()
        .set_task_instance_id("filter_patrol_info_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="patrol_info",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_patrol_info_events") or {}),
        )
        .call()
    )

    normalize_pi_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_pi_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_patrol_info_events,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_pi_values") or {}),
        )
        .call()
    )

    rename_patrol_info = (
        map_columns.validate()
        .set_task_instance_id("rename_patrol_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "event_details__patrolinfomation_participants": "participants",
                "event_details__patrolinfomation_patrolpurpose": "purpose",
                "event_details__patrolinfomation_personwhoauthorised": "authorized_by",
                "event_details__patrolinfomation_transporttype": "transport_type",
                "patrols": "patrol_id",
            },
            df=normalize_pi_values,
            **(params_dict.get("rename_patrol_info") or {}),
        )
        .call()
    )

    patrol_info_summary = (
        summarize_df.validate()
        .set_task_instance_id("patrol_info_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["purpose"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=rename_patrol_info,
            **(params_dict.get("patrol_info_summary") or {}),
        )
        .call()
    )

    capitalize_patrol_text = (
        capitalize_text.validate()
        .set_task_instance_id("capitalize_patrol_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_info_summary,
            column="purpose",
            **(params_dict.get("capitalize_patrol_text") or {}),
        )
        .call()
    )

    include_pat_totals = (
        add_totals_row.validate()
        .set_task_instance_id("include_pat_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["purpose"],
            label="Total",
            df=capitalize_patrol_text,
            **(params_dict.get("include_pat_totals") or {}),
        )
        .call()
    )

    persist_patrol_df = (
        persist_df.validate()
        .set_task_instance_id("persist_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="patrol_purpose_summary",
            df=include_pat_totals,
            **(params_dict.get("persist_patrol_df") or {}),
        )
        .call()
    )

    rename_participants = (
        map_name_values.validate()
        .set_task_instance_id("rename_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_patrol_info,
            column="participants",
            **(params_dict.get("rename_participants") or {}),
        )
        .call()
    )

    filter_null_patrols = (
        filter_non_empty_values.validate()
        .set_task_instance_id("filter_null_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_participants,
            column="patrol_id",
            **(params_dict.get("filter_null_patrols") or {}),
        )
        .call()
    )

    replace_transport_unspecified = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_transport_unspecified")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_null_patrols,
            columns=["transport_type"],
            label="unspecified",
            **(params_dict.get("replace_transport_unspecified") or {}),
        )
        .call()
    )

    explode_patrol_columns = (
        explode_multiple_columns.validate()
        .set_task_instance_id("explode_patrol_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_transport_unspecified,
            columns=["patrol_id", "participants"],
            reset_index=True,
            **(params_dict.get("explode_patrol_columns") or {}),
        )
        .call()
    )

    get_patrols_from_info = (
        get_patrol_values.validate()
        .set_task_instance_id("get_patrols_from_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=explode_patrol_columns,
            patrols_column="patrol_id",
            client=er_client_name,
            batch_size=15,
            **(params_dict.get("get_patrols_from_info") or {}),
        )
        .call()
    )

    get_patrol_obs = (
        custom_get_patrol_observations_from_patrols_df.validate()
        .set_task_instance_id("get_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            patrols_df=get_patrols_from_info,
            include_patrol_details=True,
            raise_on_empty=True,
            sub_page_size=150,
            **(params_dict.get("get_patrol_obs") or {}),
        )
        .call()
    )

    drop_values_patrol_info = (
        map_columns.validate()
        .set_task_instance_id("drop_values_patrol_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=["geometry", "reported_by", "index", "serial_number"],
            retain_columns=[],
            rename_columns={
                "authorized_by": "authorized_by",
                "event_details__updates": "updates",
            },
            df=explode_patrol_columns,
            **(params_dict.get("drop_values_patrol_info") or {}),
        )
        .call()
    )

    merge_patrol_events_obs = (
        merge_dataframes.validate()
        .set_task_instance_id("merge_patrol_events_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_df=get_patrol_obs,
            right_df=drop_values_patrol_info,
            on="patrol_id",
            how="left",
            preserve_left_index=True,
            **(params_dict.get("merge_patrol_events_obs") or {}),
        )
        .call()
    )

    obs_relocs = (
        process_relocations.validate()
        .set_task_instance_id("obs_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=merge_patrol_events_obs,
            relocs_columns=[
                "extra__id",
                "extra__created_at",
                "extra__subject_id",
                "geometry",
                "groupby_col",
                "fixtime",
                "junk_status",
                "patrol_id",
                "patrol_title",
                "patrol_serial_number",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type",
                "patrol_status",
                "patrol_subject",
                "patrol_type__value",
                "participants",
                "purpose",
                "transport_type",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("obs_relocs") or {}),
        )
        .call()
    )

    persist_relocs = (
        persist_df.validate()
        .set_task_instance_id("persist_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            filename="patrol_relocations",
            df=obs_relocs,
            **(params_dict.get("persist_relocs") or {}),
        )
        .call()
    )

    filter_foot_patrols = (
        filter_df.validate()
        .set_task_instance_id("filter_foot_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="foot",
            df=obs_relocs,
            reset_index=False,
            **(params_dict.get("filter_foot_patrols") or {}),
        )
        .call()
    )

    filter_vehicle_patrols = (
        filter_df.validate()
        .set_task_instance_id("filter_vehicle_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="vehicle",
            df=obs_relocs,
            reset_index=False,
            **(params_dict.get("filter_vehicle_patrols") or {}),
        )
        .call()
    )

    filter_motor_patrols = (
        filter_df.validate()
        .set_task_instance_id("filter_motor_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="motorbike",
            df=obs_relocs,
            reset_index=False,
            **(params_dict.get("filter_motor_patrols") or {}),
        )
        .call()
    )

    filter_unspecified_patrols = (
        filter_df.validate()
        .set_task_instance_id("filter_unspecified_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="unspecified",
            df=obs_relocs,
            reset_index=False,
            **(params_dict.get("filter_unspecified_patrols") or {}),
        )
        .call()
    )

    vehicle_trajs = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("vehicle_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_vehicle_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.35,
                "max_length_meters": 5000.0,
                "max_time_secs": 18000.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 100.0,
                "min_speed_kmhr": 10.0,
            },
            **(params_dict.get("vehicle_trajs") or {}),
        )
        .call()
    )

    motor_trajs = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("motor_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_motor_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.35,
                "max_length_meters": 5000.0,
                "max_time_secs": 18000.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 100.0,
                "min_speed_kmhr": 10.0,
            },
            **(params_dict.get("motor_trajs") or {}),
        )
        .call()
    )

    foot_trajs = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("foot_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_foot_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.001,
                "max_length_meters": 5000.0,
                "max_time_secs": 14400.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 9.0,
                "min_speed_kmhr": 0.5,
            },
            **(params_dict.get("foot_trajs") or {}),
        )
        .call()
    )

    temporal_foot_traj = (
        add_temporal_index.validate()
        .set_task_instance_id("temporal_foot_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=foot_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("temporal_foot_traj") or {}),
        )
        .call()
    )

    temporal_vehicle_traj = (
        add_temporal_index.validate()
        .set_task_instance_id("temporal_vehicle_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=vehicle_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("temporal_vehicle_traj") or {}),
        )
        .call()
    )

    temporal_motor_traj = (
        add_temporal_index.validate()
        .set_task_instance_id("temporal_motor_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=motor_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("temporal_motor_traj") or {}),
        )
        .call()
    )

    rename_foot_trajs = (
        map_columns.validate()
        .set_task_instance_id("rename_foot_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=["heading", "extra__created_at", "extra__id"],
            retain_columns=[],
            rename_columns={
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject_name",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type_id",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
            },
            df=temporal_foot_traj,
            **(params_dict.get("rename_foot_trajs") or {}),
        )
        .call()
    )

    rename_vehicle_trajs = (
        map_columns.validate()
        .set_task_instance_id("rename_vehicle_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=["heading", "extra__created_at", "extra__id"],
            retain_columns=[],
            rename_columns={
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject_name",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type_id",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
            },
            df=temporal_vehicle_traj,
            **(params_dict.get("rename_vehicle_trajs") or {}),
        )
        .call()
    )

    rename_motor_trajs = (
        map_columns.validate()
        .set_task_instance_id("rename_motor_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=["heading", "extra__created_at", "extra__id"],
            retain_columns=[],
            rename_columns={
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject_name",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type_id",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
            },
            df=temporal_motor_traj,
            **(params_dict.get("rename_motor_trajs") or {}),
        )
        .call()
    )

    foot_patrol_metrics = (
        summarize_df.validate()
        .set_task_instance_id("foot_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_foot_trajs,
            **(params_dict.get("foot_patrol_metrics") or {}),
        )
        .call()
    )

    add_fp_metrics_totals = (
        add_totals_row.validate()
        .set_task_instance_id("add_fp_metrics_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["patrol_type_value"],
            label="Total",
            df=foot_patrol_metrics,
            **(params_dict.get("add_fp_metrics_totals") or {}),
        )
        .call()
    )

    persist_foot_df = (
        persist_df.validate()
        .set_task_instance_id("persist_foot_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="foot_patrol_efforts",
            df=add_fp_metrics_totals,
            **(params_dict.get("persist_foot_df") or {}),
        )
        .call()
    )

    apply_footp_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_footp_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="foot_patrol_colors",
            colormap="tab20",
            df=rename_foot_trajs,
            **(params_dict.get("apply_footp_colormap") or {}),
        )
        .call()
    )

    filter_foot_patrol_cols = (
        filter_columns.validate()
        .set_task_instance_id("filter_foot_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=apply_footp_colormap,
            columns=[
                "timespan_seconds",
                "dist_meters",
                "geometry",
                "patrol_type_value",
                "foot_patrol_colors",
            ],
            exclude=[],
            **(params_dict.get("filter_foot_patrol_cols") or {}),
        )
        .call()
    )

    generate_foot_layers = (
        create_path_layer.validate()
        .set_task_instance_id("generate_foot_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_color": "foot_patrol_colors",
                "get_width": 1.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 6,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Patrol Type",
                "label_column": "patrol_type_value",
                "color_column": "foot_patrol_colors",
                "sort": "ascending",
            },
            geodataframe=filter_foot_patrol_cols,
            data_url=None,
            **(params_dict.get("generate_foot_layers") or {}),
        )
        .call()
    )

    combine_foot_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_foot_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_foot_layers,
            **(params_dict.get("combine_foot_layers") or {}),
        )
        .call()
    )

    global_zoom_value = (
        view_state_deck_gdf.validate()
        .set_task_instance_id("global_zoom_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            gdf=overall_grazing_zones,
            **(params_dict.get("global_zoom_value") or {}),
        )
        .call()
    )

    draw_foot_map = (
        draw_map.validate()
        .set_task_instance_id("draw_foot_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_foot_layers,
            view_state=global_zoom_value,
            **(params_dict.get("draw_foot_map") or {}),
        )
        .call()
    )

    persist_foot_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_foot_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_foot_map,
            filename="foot_patrols_map.html",
            **(params_dict.get("persist_foot_urls") or {}),
        )
        .call()
    )

    vehicle_patrol_metrics = (
        summarize_df.validate()
        .set_task_instance_id("vehicle_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_vehicle_trajs,
            **(params_dict.get("vehicle_patrol_metrics") or {}),
        )
        .call()
    )

    add_vh_metrics_totals = (
        add_totals_row.validate()
        .set_task_instance_id("add_vh_metrics_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["patrol_type_value"],
            label="Total",
            df=vehicle_patrol_metrics,
            **(params_dict.get("add_vh_metrics_totals") or {}),
        )
        .call()
    )

    persist_vehicle_df = (
        persist_df.validate()
        .set_task_instance_id("persist_vehicle_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_vh_metrics_totals,
            filename="vehicle_patrol_efforts",
            **(params_dict.get("persist_vehicle_df") or {}),
        )
        .call()
    )

    apply_vehicle_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_vehicle_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="colors",
            colormap="tab20",
            df=rename_vehicle_trajs,
            **(params_dict.get("apply_vehicle_colormap") or {}),
        )
        .call()
    )

    filter_vehicle_patrol_cols = (
        filter_columns.validate()
        .set_task_instance_id("filter_vehicle_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=apply_vehicle_colormap,
            columns=[
                "timespan_seconds",
                "dist_meters",
                "geometry",
                "patrol_type_value",
                "colors",
            ],
            exclude=[],
            **(params_dict.get("filter_vehicle_patrol_cols") or {}),
        )
        .call()
    )

    generate_vehicle_layers = (
        create_path_layer.validate()
        .set_task_instance_id("generate_vehicle_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_color": "colors",
                "get_width": 1.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 6,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Patrol Type",
                "label_column": "patrol_type_value",
                "color_column": "colors",
                "sort": "ascending",
            },
            geodataframe=filter_vehicle_patrol_cols,
            data_url=None,
            **(params_dict.get("generate_vehicle_layers") or {}),
        )
        .call()
    )

    combine_vehicle_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_vehicle_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_vehicle_layers,
            **(params_dict.get("combine_vehicle_layers") or {}),
        )
        .call()
    )

    draw_vehicle_map = (
        draw_map.validate()
        .set_task_instance_id("draw_vehicle_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_vehicle_layers,
            view_state=global_zoom_value,
            **(params_dict.get("draw_vehicle_map") or {}),
        )
        .call()
    )

    persist_vehicle_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_vehicle_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_vehicle_map,
            filename="vehicle_patrols_map.html",
            **(params_dict.get("persist_vehicle_urls") or {}),
        )
        .call()
    )

    motor_patrol_metrics = (
        summarize_df.validate()
        .set_task_instance_id("motor_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_motor_trajs,
            **(params_dict.get("motor_patrol_metrics") or {}),
        )
        .call()
    )

    add_mb_metrics_totals = (
        add_totals_row.validate()
        .set_task_instance_id("add_mb_metrics_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["patrol_type_value"],
            label="Total",
            df=motor_patrol_metrics,
            **(params_dict.get("add_mb_metrics_totals") or {}),
        )
        .call()
    )

    persist_motor_df = (
        persist_df.validate()
        .set_task_instance_id("persist_motor_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_mb_metrics_totals,
            filename="motorbike_patrol_efforts",
            **(params_dict.get("persist_motor_df") or {}),
        )
        .call()
    )

    apply_motor_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_motor_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="patrol_type_value",
            output_column_name="colors",
            colormap="tab20",
            df=rename_motor_trajs,
            **(params_dict.get("apply_motor_colormap") or {}),
        )
        .call()
    )

    filter_motor_patrol_cols = (
        filter_columns.validate()
        .set_task_instance_id("filter_motor_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=apply_motor_colormap,
            columns=[
                "timespan_seconds",
                "dist_meters",
                "geometry",
                "patrol_type_value",
                "colors",
            ],
            exclude=[],
            **(params_dict.get("filter_motor_patrol_cols") or {}),
        )
        .call()
    )

    generate_motor_layers = (
        create_path_layer.validate()
        .set_task_instance_id("generate_motor_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_color": "colors",
                "get_width": 1.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 6,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Patrol Type",
                "label_column": "patrol_type_value",
                "color_column": "colors",
                "sort": "ascending",
            },
            geodataframe=filter_motor_patrol_cols,
            data_url=None,
            **(params_dict.get("generate_motor_layers") or {}),
        )
        .call()
    )

    combine_motor_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_motor_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_motor_layers,
            **(params_dict.get("combine_motor_layers") or {}),
        )
        .call()
    )

    draw_motor_map = (
        draw_map.validate()
        .set_task_instance_id("draw_motor_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_motor_layers,
            view_state=global_zoom_value,
            **(params_dict.get("draw_motor_map") or {}),
        )
        .call()
    )

    persist_motor_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_motor_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_motor_map,
            filename="motorbike_patrols_map.html",
            **(params_dict.get("persist_motor_urls") or {}),
        )
        .call()
    )

    merge_trajs = (
        merge_multiple_df.validate()
        .set_task_instance_id("merge_trajs")
        .handle_errors()
        .with_tracing()
        .partial(
            list_df=[foot_trajs, vehicle_trajs, motor_trajs],
            ignore_index=True,
            sort=False,
            **(params_dict.get("merge_trajs") or {}),
        )
        .call()
    )

    rename_combined_trajs = (
        map_columns.validate()
        .set_task_instance_id("rename_combined_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=["heading", "extra__created_at", "extra__id"],
            retain_columns=[],
            rename_columns={
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject_name",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type_id",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
                "extra__participants": "participants",
            },
            df=merge_trajs,
            **(params_dict.get("rename_combined_trajs") or {}),
        )
        .call()
    )

    persist_trajectories_data = (
        persist_df.validate()
        .set_task_instance_id("persist_trajectories_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            df=rename_combined_trajs,
            filename="patrol_trajectories",
            **(params_dict.get("persist_trajectories_data") or {}),
        )
        .call()
    )

    ranger_patrol_metrics = (
        summarize_df.validate()
        .set_task_instance_id("ranger_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["participants"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                    "decimal_places": 0,
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            reset_index=True,
            df=rename_combined_trajs,
            **(params_dict.get("ranger_patrol_metrics") or {}),
        )
        .call()
    )

    replace_ranger_nulls = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_ranger_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=ranger_patrol_metrics,
            columns=["participants"],
            label="Unspecified",
            **(params_dict.get("replace_ranger_nulls") or {}),
        )
        .call()
    )

    add_ranger_metrics_totals = (
        add_totals_row.validate()
        .set_task_instance_id("add_ranger_metrics_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["participants"],
            label="Total",
            df=replace_ranger_nulls,
            **(params_dict.get("add_ranger_metrics_totals") or {}),
        )
        .call()
    )

    persist_total_df = (
        persist_df.validate()
        .set_task_instance_id("persist_total_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_ranger_metrics_totals,
            filename="overall_patrol_efforts",
            **(params_dict.get("persist_total_df") or {}),
        )
        .call()
    )

    patrol_grid_visits = (
        create_patrol_coverage_grid.validate()
        .set_task_instance_id("patrol_grid_visits")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grid_cell_size=1000,
            trajs=rename_combined_trajs,
            **(params_dict.get("patrol_grid_visits") or {}),
        )
        .call()
    )

    apply_classification_grid = (
        apply_classification.validate()
        .set_task_instance_id("apply_classification_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            label_options={"label_ranges": False, "label_decimals": 1},
            classification_options={"k": 5, "scheme": "equal_interval"},
            df=patrol_grid_visits,
            **(params_dict.get("apply_classification_grid") or {}),
        )
        .call()
    )

    apply_grid_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_grid_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn_r",
            output_column_name="density_colors",
            df=apply_classification_grid,
            **(params_dict.get("apply_grid_colormap") or {}),
        )
        .call()
    )

    generate_grid_layers = (
        create_geojson_layer.validate()
        .set_task_instance_id("generate_grid_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.75,
                "get_line_width": 0.85,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Visits",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            geodataframe=apply_grid_colormap,
            data_url=None,
            **(params_dict.get("generate_grid_layers") or {}),
        )
        .call()
    )

    combine_grid_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_grid_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_grid_layers,
            **(params_dict.get("combine_grid_layers") or {}),
        )
        .call()
    )

    draw_grid_map = (
        draw_map.validate()
        .set_task_instance_id("draw_grid_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_grid_layers,
            view_state=global_zoom_value,
            **(params_dict.get("draw_grid_map") or {}),
        )
        .call()
    )

    persist_grid_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_grid_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_grid_map,
            filename="patrol_coverage_map.html",
            **(params_dict.get("persist_grid_urls") or {}),
        )
        .call()
    )

    compute_patrol_occupancy = (
        compute_occupancy.validate()
        .set_task_instance_id("compute_patrol_occupancy")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            coverage_grid_gdf=patrol_grid_visits,
            regions_gdf=conservancy_gdf,
            crs="epsg:4326",
            **(params_dict.get("compute_patrol_occupancy") or {}),
        )
        .call()
    )

    round_off_patrol = (
        round_values.validate()
        .set_task_instance_id("round_off_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=compute_patrol_occupancy,
            column="occupancy_percentage",
            decimals=2,
            **(params_dict.get("round_off_patrol") or {}),
        )
        .call()
    )

    persist_occupancy_df = (
        persist_df.validate()
        .set_task_instance_id("persist_occupancy_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=round_off_patrol,
            filename="patrol_coverage",
            **(params_dict.get("persist_occupancy_df") or {}),
        )
        .call()
    )

    convert_tevents_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_tevents_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_total_events,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_tevents_png") or {}),
        )
        .call()
    )

    convert_grid_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_grid_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_grid_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_grid_png") or {}),
        )
        .call()
    )

    convert_motor_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_motor_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_motor_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 25000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_motor_png") or {}),
        )
        .call()
    )

    convert_foot_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_foot_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_foot_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_foot_png") or {}),
        )
        .call()
    )

    convert_vehicle_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_vehicle_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_vehicle_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_vehicle_png") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
